version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - /home/obet/projects/docker-course-project/frontend:/home/node/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "start"]
  tests:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - /home/obet/projects/docker-course-project/frontend:/home/node/app
    command: ["npm", "run", "test"]
